import { Milestone, MilestoneId } from './types';
import prePregnancyImg from './Pre Pregnancy.png';
import earlyPregnancyImg from './early pregnancy.png';
import latePregnancyImg from './Late pregnancy.png';
import postpartumImg from './Postpartum.png';
import infantImg from './infant.png';
import toddlerImg from './toddler.png';

export const JOURNEY_DATA: Milestone[] = [
  {
    id: MilestoneId.PRE_PREGNANCY,
    title: "Pre-Pregnancy (Try to Conceive)",
    subtitle: "Fertility & Preparation",
    imageUrl: prePregnancyImg,
    description: "Your health before conception is the blueprint for your baby's future. Focus on fertility, nutritional reserves, and education.",
    expertTip: "Start Folic Acid at least 3 months before conception to reduce neural tube defect risks by up to 70%.",
    clinicalInsight: "Optimal fertility starts with hormonal balance and micronutrient density. We support both parents in this foundation stage.",
    checklist: [
      { id: 's1-mom-1', name: 'Folic Acid supplements (400-800 mcg)', category: 'Mom Care & Fertility', description: 'Essential daily intake for early neurological development.' },
      { id: 's1-mom-2', name: 'Pre-conception multivitamins', category: 'Mom Care & Fertility', description: 'Comprehensive nutrient blend to prepare the body for pregnancy.' },
      { id: 's1-mom-3', name: 'Fertility support vitamins - Women', category: 'Mom Care & Fertility', description: 'Optimizes egg quality and hormonal regulation.' },
      { id: 's1-mom-4', name: 'Fertility support vitamins - Men', category: 'Mom Care & Fertility', description: 'Supports sperm health, motility, and count.' },
      { id: 's1-mom-5', name: 'Omega-3 / DHA', category: 'Mom Care & Fertility', description: 'Vital for cardiovascular health and inflammation control.' },
      { id: 's1-mom-6', name: 'Vitamin D supplements', category: 'Mom Care & Fertility', description: 'Key for immune support and reproductive health.' },
      { id: 's1-mom-7', name: 'Zinc & antioxidant supplements', category: 'Mom Care & Fertility', description: 'Protects reproductive cells from oxidative stress.' },
      { id: 's1-test-1', name: 'Ovulation test kits', category: 'Fertility Tracking & Testing', description: 'Predicts fertile window for timed conception.' },
      { id: 's1-test-2', name: 'Pregnancy test kits', category: 'Fertility Tracking & Testing', description: 'Early detection with high sensitivity.' },
      { id: 's1-test-3', name: 'Fertility-friendly lubricants', category: 'Fertility Tracking & Testing', description: 'Sperm-safe hydration to facilitate conception.' }
    ]
  },
  {
    id: MilestoneId.EARLY_PREGNANCY,
    title: "Early Pregnancy",
    subtitle: "Fetal Development & Symptom Control",
    imageUrl: earlyPregnancyImg,
    description: "Weeks 1-13 are critical for organogenesis. This stage focuses on symptom relief and preventing the intense fatigue of the first trimester.",
    expertTip: "Small, frequent meals and ginger-based supplements can help manage morning sickness effectively.",
    clinicalInsight: "Iron and Magnesium requirements spike early. Proper supplementation prevents maternal depletion and supports blood volume expansion.",
    checklist: [
      { id: 's2-nut-1', name: 'Prenatal multivitamins (early stage)', category: 'Mom Nutrition (Internal)', description: 'Formulated for the first trimester demands.' },
      { id: 's2-nut-2', name: 'Folic Acid + DHA combinations', category: 'Mom Nutrition (Internal)', description: 'Dual support for neural and visual development.' },
      { id: 's2-nut-3', name: 'Iron supplements', category: 'Mom Nutrition (Internal)', description: 'Prevents anemia as blood volume increases.' },
      { id: 's2-nut-4', name: 'Calcium + Vitamin D', category: 'Mom Nutrition (Internal)', description: 'Essential for developing fetal skeletal structure.' },
      { id: 's2-nut-5', name: 'Magnesium', category: 'Mom Nutrition (Internal)', description: 'Relieves muscle cramps and supports relaxation.' },
      { id: 's2-nut-6', name: 'Omega-3 / DHA', category: 'Mom Nutrition (Internal)', description: 'Vital for cardiovascular health and inflammation control.' },
      { id: 's2-symp-1', name: 'Morning sickness relief (ginger, vitamin B6)', category: 'Symptom Management', description: 'Natural easing of nausea and digestive upset.' },
      { id: 's2-symp-2', name: 'Digestive comfort supplements', category: 'Symptom Management', description: 'Aids digestion and alleviates heartburn.' },
      { id: 's2-body-1', name: 'Anti-stretch mark creams (preventive)', category: 'Mom Body Care', description: 'Prepares skin elasticity for stretching.' },
      { id: 's2-body-2', name: 'Anti-stretch mark oils', category: 'Mom Body Care', description: 'Deeply nourishes and hydrates expanding skin.' },
      { id: 's2-body-3', name: 'Gentle body moisturizers (sensitive skin)', category: 'Mom Body Care', description: 'Hypoallergenic hydration for sensitive pregnancy skin.' }
    ]
  },
  {
    id: MilestoneId.LATE_PREGNANCY,
    title: "Late Pregnancy & Preparing for Delivery",
    subtitle: "Comfort & Hospital Readiness",
    imageUrl: latePregnancyImg,
    description: "The third trimester is about skeletal support, preparing your hospital bag, and ensuring your skin is protected as it stretches most.",
    expertTip: "Pack your hospital bag by week 35. Include lanolin cream to prevent nursing discomfort from day one.",
    clinicalInsight: "Compression and pelvic support are key to managing late-pregnancy discomfort and maintaining healthy circulation.",
    checklist: [
      { id: 's3-nut-1', name: 'Prenatal vitamins (late stage)', category: 'Mom Nutrition', description: 'Supports rapid fetal growth and maternal energy.' },
      { id: 's3-nut-2', name: 'Iron supplements', category: 'Mom Nutrition', description: 'Prevents anemia as blood volume increases.' },
      { id: 's3-nut-3', name: 'Calcium + Vitamin D', category: 'Mom Nutrition', description: 'Essential for developing fetal skeletal structure.' },
      { id: 's3-nut-4', name: 'Magnesium (cramps & sleep)', category: 'Mom Nutrition', description: 'Helps reduce leg cramps and improves sleep.' },
      { id: 's3-body-1', name: 'Anti-stretch mark creams (intensive)', category: 'Mom Body & Physical Support', description: 'Rich formulas for max skin elasticity.' },
      { id: 's3-body-2', name: 'Anti-stretch mark oils & butters', category: 'Mom Body & Physical Support', description: 'Locks in moisture for growing bellies.' },
      { id: 's3-body-3', name: 'Maternity support belts', category: 'Mom Body & Physical Support', description: 'Relieves back pressure and pelvic weight.' },
      { id: 's3-body-4', name: 'Compression socks / stockings', category: 'Mom Body & Physical Support', description: 'Promotes circulation and reduces swelling.' },
      { id: 's3-hosp-m1', name: 'Maternity pads', category: 'Hospital Bag – Mom', description: 'Heavy-duty absorbency for postpartum care.' },
      { id: 's3-hosp-m2', name: 'Disposable mesh underwear', category: 'Hospital Bag – Mom', description: 'Breathable, secure fit for recovery days.' },
      { id: 's3-hosp-m3', name: 'Nursing bras', category: 'Hospital Bag – Mom', description: 'Comfortable access for breastfeeding.' },
      { id: 's3-hosp-m4', name: 'Nipple creams (lanolin & alternatives)', category: 'Hospital Bag – Mom', description: 'Soothes and protects sensitive nursing skin.' },
      { id: 's3-hosp-m5', name: 'Disposable breast pads', category: 'Hospital Bag – Mom', description: 'Absorbs leakage to keep skin dry.' },
      { id: 's3-hosp-m6', name: 'Peri-bottles (post-delivery hygiene)', category: 'Hospital Bag – Mom', description: 'Gentle water cleansing for sensitive areas.' },
      { id: 's3-hosp-b1', name: 'Newborn diapers (Size 0 / 1)', category: 'Hospital Bag – Baby', description: 'Gentle fit for newborn delicate skin.' },
      { id: 's3-hosp-b2', name: 'Water wipes / fragrance-free wipes', category: 'Hospital Bag – Baby', description: 'Purest cleaning for first diaper changes.' },
      { id: 's3-hosp-b3', name: 'Diaper rash creams', category: 'Hospital Bag – Baby', description: 'Protective barrier against moisture.' },
      { id: 's3-hosp-b4', name: 'Swaddles & muslins', category: 'Hospital Bag – Baby', description: 'Cozy and breathable for secure sleep.' },
      { id: 's3-hosp-b5', name: 'First outfits & hats', category: 'Hospital Bag – Baby', description: 'Soft, warm clothing for the first journey.' }
    ]
  },
  {
    id: MilestoneId.POST_DELIVERY,
    title: "Postpartum & New Baby (0–6 Months)",
    subtitle: "Recovery, Feeding & Bonding",
    imageUrl: postpartumImg,
    description: "The first 6 months focus on maternal recovery, establishing feeding routines, and ensuring baby's hygiene and safety.",
    expertTip: "Hydration is the engine of milk supply. Keep a water bottle with you at every feeding session.",
    clinicalInsight: "Vitamin D is essential for newborns as it is not naturally high in breast milk. Daily drops are recommended.",
    checklist: [
      { id: 's4-mom-1', name: 'Post-natal multivitamins', category: 'Mom Care & Breastfeeding', description: 'Supports physical recovery and energy.' },
      { id: 's4-mom-2', name: 'Breastfeeding support supplements / teas', category: 'Mom Care & Breastfeeding', description: 'Natural aids to enhance milk production.' },
      { id: 's4-mom-3', name: 'Nursing bras', category: 'Mom Care & Breastfeeding', description: 'Comfortable access for breastfeeding.' },
      { id: 's4-mom-4', name: 'Breast pumps (manual & electric)', category: 'Mom Care & Breastfeeding', description: 'Efficient milk expression options.' },
      { id: 's4-mom-5', name: 'Milk storage bags', category: 'Mom Care & Breastfeeding', description: 'Sterile freezing and storage solution.' },
      { id: 's4-mom-6', name: 'Nipple care creams', category: 'Mom Care & Breastfeeding', description: 'Daily protection against soreness.' },
      { id: 's4-mom-7', name: 'C-section scar healing gels', category: 'Mom Care & Breastfeeding', description: 'Promotes healthy skin regeneration.' },
      { id: 's4-mom-8', name: 'Silicone scar patches', category: 'Mom Care & Breastfeeding', description: 'Flattens and softens scar tissue.' },
      { id: 's4-mom-9', name: 'Anti-stretch mark creams & oils (post-delivery recovery)', category: 'Mom Care & Breastfeeding', description: 'Helps skin regain tone and texture.' },
      { id: 's4-mom-10', name: 'Hydration accessories (water bottles)', category: 'Mom Care & Breastfeeding', description: 'Essential for maintaining milk supply.' },
      { id: 's4-baby-1', name: 'Infant Formula Stage 1 (0-6 months)', category: 'Baby Nutrition', description: 'Complete early nutrition source.' },
      { id: 's4-baby-2', name: 'Comfort formula (anti-colic)', category: 'Baby Nutrition', description: 'Eases gas and digestive discomfort.' },
      { id: 's4-baby-3', name: 'HA / Hypoallergenic formula', category: 'Baby Nutrition', description: 'For babies with protein sensitivities.' },
      { id: 's4-baby-4', name: 'LF (Lactose-Free) formula', category: 'Baby Nutrition', description: 'For temporary lactose intolerance.' },
      { id: 's4-baby-5', name: 'Goat-milk formula', category: 'Baby Nutrition', description: 'Gentle alternative easy on digestion.' },
      { id: 's3-add-3', name: 'Baby shampoo', category: 'Baby Toiletries (Hair & Skin)', description: 'Tear-free scalp care.' },
      { id: 's3-add-4', name: 'Baby body wash', category: 'Baby Toiletries (Hair & Skin)', description: 'Gentle cleansing for newborn skin.' },
      { id: 's4-toil-3', name: 'Baby lotion', category: 'Baby Toiletries (Hair & Skin)', description: 'Daily hydration after bath time.' },
      { id: 's3-add-5', name: 'Baby oils', category: 'Baby Toiletries (Hair & Skin)', description: 'For moisture and massage.' },
      { id: 's4-toil-5', name: 'Barrier / protective creams', category: 'Baby Toiletries (Hair & Skin)', description: 'Shields skin from irritants.' },
      { id: 's4-diap-1', name: 'Newborn diapers', category: 'Baby Diapers & Wipes', description: 'Soft absorbent protection.' },
      { id: 's4-diap-2', name: 'Sensitive baby wipes', category: 'Baby Diapers & Wipes', description: 'Hypoallergenic cleaning.' },
      { id: 's4-diap-3', name: 'Water wipes', category: 'Baby Diapers & Wipes', description: 'Minimalist cleaning for pure skin.' },
      { id: 's4-diap-4', name: 'Diaper rash creams', category: 'Baby Diapers & Wipes', description: 'Protective barrier against moisture.' },
      { id: 's3-add-2', name: 'Baby bottles & nipples', category: 'Baby Accessories & Safety', description: 'For expressed milk or formula feeding.' },
      { id: 's4-acc-2', name: 'Bottle sterilizers', category: 'Baby Accessories & Safety', description: 'Steam clean to kill bacteria.' },
      { id: 's4-acc-3', name: 'Bottle warmers', category: 'Baby Accessories & Safety', description: 'Safe, even heating for milk.' },
      { id: 's4-acc-4', name: 'Milk dividers / dispensers', category: 'Baby Accessories & Safety', description: 'Portable powder storage.' },
      { id: 's4-acc-5', name: 'Pacifiers & soothers', category: 'Baby Accessories & Safety', description: 'Comforts baby and supports sleep.' },
      { id: 's4-acc-6', name: 'Baby monitors', category: 'Baby Accessories & Safety', description: 'Audio/video safety checks.' },
      { id: 's4-acc-7', name: 'Baby clothes detergent (hypoallergenic)', category: 'Baby Accessories & Safety', description: 'Safe washing for baby skins.' },
      { id: 's4-gear-1', name: 'Strollers / prams', category: 'Mobility & Big Gear', description: 'Comfortable transport for baby.' },
      { id: 's4-gear-2', name: 'Baby carriage systems', category: 'Mobility & Big Gear', description: 'Versatile travel solutions.' },
      { id: 's4-gear-3', name: 'Infant car seats', category: 'Mobility & Big Gear', description: 'Essential road safety.' },
      { id: 's4-gear-4', name: 'Bassinets / cribs', category: 'Mobility & Big Gear', description: 'Safe sleep environments.' }
    ]
  },
  {
    id: MilestoneId.INFANT_CARE,
    title: "Infants (6–12 Months) & Mom Care",
    subtitle: "Growth, Weaning & Development",
    imageUrl: infantImg,
    description: "As baby starts solids and begins crawling, safety and weaning foods become the priority, alongside ongoing maternal wellness.",
    expertTip: "Introduce iron-fortified cereals as baby's natural iron stores begin to deplete after 6 months.",
    clinicalInsight: "Teething causes significant discomfort; cooling rings and sugar-free gels are safe ways to provide relief.",
    checklist: [
      { id: 's5-nut-1', name: 'Infant Formula Stage 2', category: 'Baby Nutrition', description: 'Tailored for older, active infants.' },
      { id: 's5-nut-2', name: 'Comfort formula', category: 'Baby Nutrition', description: 'Continued support for digestion.' },
      { id: 's5-nut-3', name: 'HA / LF / Goat milk variants', category: 'Baby Nutrition', description: 'Specialized options for intolerances.' },
      { id: 's5-nut-4', name: 'Iron-fortified baby cereals', category: 'Baby Nutrition', description: 'Essential first solid foods.' },
      { id: 's5-nut-5', name: 'Weaning foods', category: 'Baby Nutrition', description: 'Purees and snacks for taste exploration.' },
      { id: 's5-toil-1', name: 'Baby shampoo', category: 'Baby Toiletries', description: 'Tear-free scalp care.' },
      { id: 's5-toil-2', name: 'Baby body wash', category: 'Baby Toiletries', description: 'Gentle cleansing for newborn skin.' },
      { id: 's5-toil-3', name: 'Moisturizing lotions', category: 'Baby Toiletries', description: 'Keeps active skin soft.' },
      { id: 's5-toil-4', name: 'Baby sunscreen (safe formulas)', category: 'Baby Toiletries', description: 'Sun protection for outdoor play.' },
      { id: 's5-diap-1', name: 'Infant diapers', category: 'Diapers & Hygiene', description: 'Larger fit with high movement flex.' },
      { id: 's5-diap-2', name: 'Wipes', category: 'Diapers & Hygiene', description: 'Cleaning essential for messier solids.' },
      { id: 's5-diap-3', name: 'Rash prevention creams', category: 'Diapers & Hygiene', description: 'Protects skin from irritation.' },
      { id: 's5-acc-1', name: 'Teething gels', category: 'Accessories & Development', description: 'Relief for sore gums.' },
      { id: 's5-acc-2', name: 'Teething rings (cooling)', category: 'Accessories & Development', description: 'Chewable comfort for teething pain.' },
      { id: 's5-acc-3', name: 'Pacifiers (6m+)', category: 'Accessories & Development', description: 'Sized correctly for oral development.' },
      { id: 's5-acc-4', name: 'Sippy cups', category: 'Accessories & Development', description: 'Training for independent drinking.' },
      { id: 's5-acc-5', name: 'Feeding bowls, spoons, bibs', category: 'Accessories & Development', description: 'Mealtime essentials.' },
      { id: 's5-acc-6', name: 'Activity mats', category: 'Accessories & Development', description: 'Stimulates large muscle movement.' },
      { id: 's5-acc-7', name: 'Developmental toys', category: 'Accessories & Development', description: 'Focuses on improved motor skills.' },
      { id: 's5-safe-1', name: 'Baby safety gates', category: 'Safety & Mobility', description: 'Secures hazardous areas.' },
      { id: 's5-safe-2', name: 'Cabinet & corner protectors', category: 'Safety & Mobility', description: 'Identifies and softens sharp edges.' },
      { id: 's5-safe-3', name: 'Baby monitors', category: 'Safety & Mobility', description: 'Audio/video safety checks.' },
      { id: 's5-safe-4', name: 'Stroller upgrades', category: 'Safety & Mobility', description: 'For more upright, engaged travel.' },
      { id: 's5-safe-5', name: 'Convertible car seats', category: 'Safety & Mobility', description: 'Adapts to growing height and weight.' },
      { id: 's5-mom-1', name: 'Post-natal / women multivitamins', category: 'Continued Mom Care', description: 'Maintains health for busy motherhood.' },
      { id: 's5-mom-2', name: 'Hair care & recovery products', category: 'Continued Mom Care', description: 'Strengthens postpartum hair.' },
      { id: 's5-mom-3', name: 'Skincare & hydration products', category: 'Continued Mom Care', description: 'Restores skin vitality.' }
    ]
  },
  {
    id: MilestoneId.TODDLER_CARE,
    title: "Toddlers (1–3 Years) & Mom Care",
    subtitle: "Independence & Immunity",
    imageUrl: toddlerImg,
    description: "Toddlers need specialized milk and immunity support. This stage also focuses on oral hygiene and home safety for active explorers.",
    expertTip: "Growing-up milks are fortified with iron and Vitamin D to ensure toddlers meet their daily requirements.",
    clinicalInsight: "The first 3 years are the most rapid period of brain development. DHA and proper nutrition remain vital.",
    checklist: [
      { id: 's6-milk-1', name: 'Toddler Formula / Growing-Up Milk (Stage 3)', category: 'Toddler Nutrition', description: 'Premium toddler formula / growing-up milk (stage 3) selected for this motherhood phase.' },
      { id: 's6-milk-2', name: 'Comfort / LF / Goat toddler milk', category: 'Toddler Nutrition', description: 'Premium comfort / lf / goat toddler milk selected for this motherhood phase.' },
      { id: 's6-milk-3', name: 'Multivitamin syrups or gummies', category: 'Toddler Nutrition', description: 'Premium multivitamin syrups or gummies selected for this motherhood phase.' },
      { id: 's6-toil-1', name: 'Kids shampoo', category: 'Toiletries & Personal Care', description: 'Premium kids shampoo selected for this motherhood phase.' },
      { id: 's6-toil-2', name: 'Hair detangler sprays', category: 'Toiletries & Personal Care', description: 'Premium hair detangler sprays selected for this motherhood phase.' },
      { id: 's6-toil-3', name: 'Kids body wash', category: 'Toiletries & Personal Care', description: 'Premium kids body wash selected for this motherhood phase.' },
      { id: 's6-toil-4', name: 'Moisturizers', category: 'Toiletries & Personal Care', description: 'Premium moisturizers selected for this motherhood phase.' },
      { id: 's6-toil-5', name: 'Sunscreen', category: 'Toiletries & Personal Care', description: 'Premium sunscreen selected for this motherhood phase.' },
      { id: 's6-diap-1', name: 'Training pants', category: 'Diapers & Training', description: 'Premium training pants selected for this motherhood phase.' },
      { id: 's6-diap-2', name: 'Pull-ups', category: 'Diapers & Training', description: 'Premium pull-ups selected for this motherhood phase.' },
      { id: 's6-diap-3', name: 'Potty seats & accessories', category: 'Diapers & Training', description: 'Premium potty seats & accessories selected for this motherhood phase.' },
      { id: 's6-oral-1', name: 'Kids toothbrushes', category: 'Oral Care', description: 'Premium kids toothbrushes selected for this motherhood phase.' },
      { id: 's6-oral-2', name: 'Fluoride toothpaste', category: 'Oral Care', description: 'Premium fluoride toothpaste selected for this motherhood phase.' },
      { id: 's6-play-1', name: 'Developmental toys', category: 'Learning & Activity', description: 'Focuses on improved motor skills.' },
      { id: 's6-play-2', name: 'Push toys', category: 'Learning & Activity', description: 'Premium push toys selected for this motherhood phase.' },
      { id: 's6-play-3', name: 'Blocks & puzzles', category: 'Learning & Activity', description: 'Premium blocks & puzzles selected for this motherhood phase.' },
      { id: 's6-play-4', name: 'Outdoor play items', category: 'Learning & Activity', description: 'Premium outdoor play items selected for this motherhood phase.' },
      { id: 's6-safe-1', name: 'Advanced home safety products', category: 'Safety & Mobility', description: 'Premium advanced home safety products selected for this motherhood phase.' },
      { id: 's6-safe-2', name: 'Toddler car seats', category: 'Safety & Mobility', description: 'Premium toddler car seats selected for this motherhood phase.' },
      { id: 's6-safe-3', name: 'Stroller alternatives', category: 'Safety & Mobility', description: 'Premium stroller alternatives selected for this motherhood phase.' },
      { id: 's6-mom-1', name: 'Energy-boosting supplements', category: 'Ongoing Mom Care', description: 'Premium energy-boosting supplements selected for this motherhood phase.' },
      { id: 's6-mom-2', name: 'Daily skincare & wellness', category: 'Ongoing Mom Care', description: 'Premium daily skincare & wellness selected for this motherhood phase.' },
      { id: 's6-mom-3', name: 'Relaxation & recovery products', category: 'Ongoing Mom Care', description: 'Premium relaxation & recovery products selected for this motherhood phase.' }
    ]
  }
];

export const JOURNEY_DATA_AR: Milestone[] = [
  {
    id: MilestoneId.PRE_PREGNANCY,
    title: "مرحلة ما قبل الحمل",
    subtitle: "الخصوبة والإعداد",
    imageUrl: prePregnancyImg,
    description: "صحتكِ قبل الحمل هي الأساس لمستقبل طفلكِ. ركزي على الخصوبة، المخزون الغذائي، والثقافة الصحية.",
    expertTip: "ابدئي بتناول حمض الفوليك قبل 3 أشهر على الأقل من الحمل لتقليل مخاطر العيوب الخلقية بنسبة تصل إلى 70%.",
    clinicalInsight: "تبدأ الخصوبة المثالية بالتوازن الهرموني وكثافة المغذيات الدقيقة لمعاينة البداية الصحية.",
    checklist: [
      { id: 's1-mom-1', name: 'مكملات حمض الفوليك (400-800 ميكروغرام)', category: 'رعاية الأم والخصوبة', description: 'جرعة يومية أساسية للتطور العصبي المبكر للجنين.' },
      { id: 's1-mom-2', name: 'فيتامينات متعددة لمرحلة ما قبل الحمل', category: 'رعاية الأم والخصوبة', description: 'مزيج مغذيات متكامل لتهيئة الجسم وتغذيته استعداداً للحمل.' },
      { id: 's1-mom-3', name: 'فيتامينات دعم الخصوبة - للنساء', category: 'رعاية الأم والخصوبة', description: 'تحسن جودة البويضات وتنظم الهرمونات الأنثوية.' },
      { id: 's1-mom-4', name: 'فيتامينات دعم الخصوبة - للرجال', category: 'رعاية الأم والخصوبة', description: 'تدعم صحة وحركة وعدد الحيوانات المنوية بشكل طبيعي.' },
      { id: 's1-mom-5', name: 'أوميغا-3 زيت السمك النقي', category: 'رعاية الأم والخصوبة', description: 'عنصر حاسم لنمو الدماغ وتطور العين لدى الجنين.' },
      { id: 's1-mom-6', name: 'فيتامين د3 (مكملات الخصوبة)', category: 'رعاية الأم والخصوبة', description: 'أساسي لدعم المناعة والصحة الإنجابية المتوازنة.' },
      { id: 's1-mom-7', name: 'الزنك المغذي ومضادات الأكسدة', category: 'رعاية الأم والخصوبة', description: 'يحمي الخلايا التناسلية الإنجابية من الإجهاد التأكسدي.' },
      { id: 's1-test-1', name: 'أجهزة اختبار الإباضة المنزلية', category: 'تتبع الخصوبة والتحليل', description: 'تساعد على تحديد أيام التبويض بدقة عالية لفرص حمل أفضل.' },
      { id: 's1-test-2', name: 'أجهزة اختبار الحمل المبكر', category: 'تتبع الخصوبة والتحليل', description: 'أجهزة فائقة الحساسية لكشف مؤشرات الحمل الأولى.' },
      { id: 's1-test-3', name: 'مرطبات مهبلية داعمة للخصوبة', category: 'تتبع الخصوبة والتحليل', description: 'مرطبات آمنة للحيوانات المنوية لتسهيل عملية التلقيح.' }
    ]
  },
  {
    id: MilestoneId.EARLY_PREGNANCY,
    title: "مرحلة بداية الحمل",
    subtitle: "تطور الجنين والسيطرة على الأعراض",
    imageUrl: earlyPregnancyImg,
    description: "الأسابيع 1-13 حاسمة لتشكل الأعضاء. تركز هذه المرحلة على تخفيف الأعراض ومنع الإرهاق الشديد.",
    expertTip: "الوجبات الصغيرة والمتكررة ومكملات الزنجبيل يمكن أن تساعد في إدارة غثيان الصباح بفعالية.",
    clinicalInsight: "تزداد الحاجة للحديد والمغنيسيوم مبكراً لدعم توسع حجم الدم ومنع استنزاف الأم.",
    checklist: [
      { id: 's2-nut-1', name: 'فيتامينات الحمل المتكاملة (المرحلة الأولى)', category: 'تغذية الأم الداخلية', description: 'تركيبة مخصصة تلائم متطلبات نمو الجنين في الثلث الأول.' },
      { id: 's2-nut-2', name: 'مكملات حمض الفوليك + أوميغا DHA المشتركة', category: 'تغذية الأم الداخلية', description: 'دعم مزدوج للتطور البصري والخلوي العصبي السليم.' },
      { id: 's2-nut-3', name: 'مكملات الحديد لزيادة الهيموغلوبين', category: 'تغذية الأم الداخلية', description: 'تحافظ على مستويات صحية وطبيعية للدم استعداداً للمخاض.' },
      { id: 's2-nut-4', name: 'الكالسيوم العلاجي + فيتامين د3', category: 'تغذية الأم الداخلية', description: 'يقوي كتلة العظام لكل من الأم وجنينها النامي.' },
      { id: 's2-nut-5', name: 'مكمل المغنيسيوم العلاجي', category: 'تغذية الأم الداخلية', description: 'يخفف من تشنجات الساق العضلية ويدعم الاسترخاء والهدوء.' },
      { id: 's2-nut-6', name: 'أوميغا-3 زيت السمك النقي', category: 'تغذية الأم الداخلية', description: 'عنصر حاسم لنمو الدماغ وتطور العين لدى الجنين.' },
      { id: 's2-symp-1', name: 'مخففات غثيان الصباح (الزنجبيل وفيتامين B6)', category: 'إدارة الأعراض المزعجة', description: 'تخفيف طبيعي آمن للغثيان واضطرابات الجهاز الهضمي.' },
      { id: 's2-symp-2', name: 'مكملات الهضم ومخففات حموضة المعدة', category: 'إدارة الأعراض المزعجة', description: 'تساعد على تلطيف جدار المعدة وتقليل الارتجاع المزعج.' },
      { id: 's2-body-1', name: 'كريمات الوقاية من علامات تمدد الجلد', category: 'العناية بالبشرة والجسد', description: 'تهيئ مرونة خلايا البشرة لتمدد منطقة البطن تدريجياً.' },
      { id: 's2-body-2', name: 'زيوت العناية وتنعيم الجلد الحساس', category: 'العناية بالبشرة والجسد', description: 'تغذي بشرة الحامل بعمق وتزيد من ليونة الأنسجة.' },
      { id: 's2-body-3', name: 'مرطب لطيف للجسم (خالٍ من العطور)', category: 'العناية بالبشرة والجسد', description: 'ترطيب آمن ومضاد للحساسية للبشرة الجافة الشديدة للحوامل.' }
    ]
  },
  {
    id: MilestoneId.LATE_PREGNANCY,
    title: "مرحلة الاستعداد للولادة",
    subtitle: "الراحة والاستعداد للولادة",
    imageUrl: latePregnancyImg,
    description: "الثلث الثالث يدور حول دعم الهيكل العظمي، وتجهيز حقيبة المستشفى، وحماية البشرة أثناء تمددها.",
    expertTip: "جهزي حقيبة المستشفى بحلول الأسبوع 35. لا تنسي كريم اللانولين.",
    clinicalInsight: "الدعم الضاغط ودعم الحوض مفاتيح لإدارة انزعاج الحمل المتأخر.",
    checklist: [
      { id: 's3-nut-1', name: 'فيتامينات الحوامل للمرحلة المتأخرة', category: 'مكملات تغذية الأم', description: 'تدعم النمو المتسارع للجنين وتمد الأم بالطاقة اللازمة للولادة.' },
      { id: 's3-nut-2', name: 'مكملات الحديد لزيادة الهيموغلوبين', category: 'مكملات تغذية الأم', description: 'تحافظ على مستويات صحية وطبيعية للدم استعداداً للمخاض.' },
      { id: 's3-nut-3', name: 'الكالسيوم العلاجي + فيتامين د3', category: 'مكملات تغذية الأم', description: 'يقوي كتلة العظام لكل من الأم وجنينها النامي.' },
      { id: 's3-nut-4', name: 'المغنيسيوم لتهدئة العضلات والمساعدة على النوم', category: 'مكملات تغذية الأم', description: 'يقلل من الأرق وتشنج الساقين الليلي المزعج.' },
      { id: 's3-body-1', name: 'كريم مركب علاجي مكثف لتمدد الجلد', category: 'العناية بالبشرة والدعم البدني', description: 'تركيبة فائقة الغنى للحد من التشققات وحماية ليونة البطن.' },
      { id: 's3-body-2', name: 'زيوت زبدة الشيا المرطبة العميقة', category: 'العناية بالبشرة والدعم البدني', description: 'تحبس الرطوبة داخل خلايا الجلد للتخفيف من الحكة.' },
      { id: 's3-body-3', name: 'حزام دعم وتخفيف ثقل الحمل', category: 'العناية بالبشرة والدعم البدني', description: 'يخفف الضغط المؤلم عن الظهر والحوض أثناء الحركة والمشي.' },
      { id: 's3-body-4', name: 'جوارب ضاغطة طبية لتنشيط الدورة الدموية', category: 'العناية بالبشرة والدعم البدني', description: 'تقلل من انتفاخ الكاحلين وتورم القدمين من الوقوف.' },
      { id: 's3-hosp-m1', name: 'فوط صحية مخصصة لفترة النفاس', category: 'حقيبة المستشفى - للأم', description: 'فوط صحية مخصصة ومريحة للغاية ومقاومة للتسرب لأيام النفاس الأولى.' },
      { id: 's3-hosp-m2', name: 'سراويل شبكية مخصصة للاستخدام الواحد', category: 'حقيبة المستشفى - للأم', description: 'سراويل مريحة وجيدة التهوية ومثالية لفترة التعافي.' },
      { id: 's3-hosp-m3', name: 'حمالات صدر الرضاعة الطبيعية القطنية', category: 'حقيبة المستشفى - للأم', description: 'خالية من الأسلاك المعدنية لتوفير أعلى مستوى من الراحة اليومية والتهوية.' },
      { id: 's3-hosp-m4', name: 'كريم اللانولين العلاجي للحلمات', category: 'حقيبة المستشفى - للأم', description: 'يرطب، يلطف ويحمي بشرة الثدي الحساسة من الالتهاب والتشقق.' },
      { id: 's3-hosp-m5', name: 'وسادات حماية الثدي القطنية المانعة للتسرب', category: 'حقيبة المستشفى - للأم', description: 'تمتص تسرب الحليب للحفاظ على الملابس جافة ونظيفة تماماً.' },
      { id: 's3-hosp-m6', name: 'مضخة ماء لتطهير منطقة الولادة اللطيف', category: 'حقيبة المستشفى - للأم', description: 'تنظيف لطيف ودافئ ومريح للغاية للمناطق الحساسة بعد الولادة.' },
      { id: 's3-hosp-b1', name: 'حفاضات حديثي الولادة (مقاس 0 / 1)', category: 'حقيبة المستشفى - للطفل', description: 'حماية ناعمة ومرنة تتناسب مع بشرة المولود الحساسة.' },
      { id: 's3-hosp-b2', name: 'مناديل مبللة مائية (خالية من العطور)', category: 'حقيبة المستشفى - للطفل', description: 'مناديل مائية نقية تماماً لتنظيف بشرة المولود بكل أمان وبشرة المولود.' },
      { id: 's3-hosp-b3', name: 'كريمات علاج طفح الحفاض والتهابات المؤخرة', category: 'حقيبة المستشفى - للطفل', description: 'تركيبة غنية بأكسيد الزنك لتهدئة وعلاج الاحمرار بسرعة وحماية الجلد.' },
      { id: 's3-hosp-b4', name: 'قماط قطني ولفافات ناعمة مريحة', category: 'حقيبة المستشفى - للطفل', description: 'يوفر دفئاً مهدئاً ويحاكي راحة الرحم لنوم عميق.' },
      { id: 's3-hosp-b5', name: 'الملابس الأولى وقبعات الرأس القطنية للطفل', category: 'حقيبة المستشفى - للطفل', description: 'ملابس فائقة النعومة لحماية وتدفئة المولود في أيامه الأولى وتناسق دافئ.' }
    ]
  },
  {
    id: MilestoneId.POST_DELIVERY,
    title: "مرحلة ما بعد الولادة",
    subtitle: "التعافي، الرضاعة والترابط",
    imageUrl: postpartumImg,
    description: "الأشهر الستة الأولى تركز على تعافي الأم، وتأسيس روتين الرضاعة، وضمان نظافة وسلامة الطفل.",
    expertTip: "الترطيب هو محرك إدرار الحليب. احتفظي بزجاجة ماء معك في كل جلسة رضاعة.",
    clinicalInsight: "فيتامين د ضروري للمواليد حيث لا يتواجد بنسب عالية في حليب الأم بشكل طبيعي.",
    checklist: [
      { id: 's4-mom-1', name: 'فيتامينات ومكملات ما بعد الولادة', category: 'صحة الأم والرضاعة', description: 'تدعم تجدد الخلايا والتعافي الجسدي ومستويات طاقة الجسم وتعويض المعادن.' },
      { id: 's4-mom-2', name: 'شاي وأعشاب إدرار الحليب الطبيعية', category: 'صحة الأم والرضاعة', description: 'مكونات عشبية آمنة ومدرة محفزة لتدفق الحليب المغذي للطفل.' },
      { id: 's4-mom-3', name: 'حمالات صدر الرضاعة الطبيعية القطنية', category: 'صحة الأم والرضاعة', description: 'خالية من الأسلاك المعدنية لتوفير أعلى مستوى من الراحة اليومية والتهوية.' },
      { id: 's4-mom-4', name: 'أجهزة شفط حليب الثدي اليدوية والكهربائية', category: 'صحة الأم والرضاعة', description: 'مضخات طبية متطورة لتنظيم وتفريغ الحليب وتخزينه بكل سلاسة.' },
      { id: 's4-mom-5', name: 'حقائب وأكياس حفظ الحليب المعقمة', category: 'صحة الأم والرضاعة', description: 'حل معقم مثالي لحفظ وتجميد حليب الأم للاستخدام اللاحق.' },
      { id: 's4-mom-6', name: 'مركبات وكريمات العناية بحلمة الثدي', category: 'صحة الأم والرضاعة', description: 'حماية يومية تمنع الآلام والتشققات المزعجة عند بدء الرضاعة.' },
      { id: 's4-mom-7', name: 'جل علاج والتحام جروح الولادة القيصرية', category: 'صحة الأم والرضاعة', description: 'كريم سليكوني طبي متطور يسرع شفاء والتئام جرح القيصرية وحمايته.' },
      { id: 's4-mom-8', name: 'لصقات السليكون لتحسين مظهر ندبات الجرح', category: 'صحة الأم والرضاعة', description: 'لصقات طبية تقلل من بروز وتغير لون ندبة جرح الولادة واستقراره.' },
      { id: 's4-mom-9', name: 'كريمات استعادة حيوية ومرونة خلايا الجلد', category: 'صحة الأم والرضاعة', description: 'تساعد الأنسجة على الانكماش الطبيعي واستعادة نضارة البشرة وشد الجلد.' },
      { id: 's4-mom-10', name: 'ملحقات الترطيب وزجاجات الشرب الفاخرة', category: 'صحة الأم والرضاعة', description: 'تذكير مستمر وضروري للأم لزيادة استهلاك السوائل يومياً.' },
      { id: 's4-baby-1', name: 'حليب الرضع للمرحلة الأولى (0-6 أشهر)', category: 'تغذية الرضيع المتكاملة', description: 'تركيبة غذائية متكاملة تلبي كافة احتياجات النمو المبكرة.' },
      { id: 's4-baby-2', name: 'حليب الرضع المضاد للمغص والغازات (Comfort)', category: 'تغذية الرضيع المتكاملة', description: 'حليب خفيف وسهل الهضم لتهدئة آلام البطن والانتفاخ الشديد.' },
      { id: 's4-baby-3', name: 'حليب الرضع المضاد للحساسية (HA)', category: 'تغذية الرضيع المتكاملة', description: 'معد خصيصاً للرضع الذين يعانون من حساسية بروتين الحليب البقري.' },
      { id: 's4-baby-4', name: 'حليب الرضع الخالي من اللاكتوز (LF)', category: 'تغذية الرضيع المتكاملة', description: 'تركيبة طبية مخصصة لحالات عدم تحمل اللاكتوز المؤقتة.' },
      { id: 's4-baby-5', name: 'حليب الرضع المعتمد على حليب الماعز', category: 'تغذية الرضيع المتكاملة', description: 'بديل طبيعي ممتاز يتميز ببروتين ناعم للغاية وسهل الهضم وبناء الخلايا.' },
      { id: 's3-add-3', name: 'شامبو لطيف ومغذي لشعر الأطفال المقوي', category: 'مستحضرات النظافة (الشعر والبشرة)', description: 'تنظيف خفيف ولطيف للغاية لخصلات شعر طفلكِ النامية.' },
      { id: 's3-add-4', name: 'غسول رغوي ناعم ومطهر لجسم الرضيع', category: 'مستحضرات النظافة (الشعر والبشرة)', description: 'تنظيف معتدل ومطهر ومناسب للاستحمام اليومي دون حدوث جفاف للبشرة.' },
      { id: 's4-toil-3', name: 'لوشن الأطفال المرطب اليومي', category: 'مستحضرات النظافة (الشعر والبشرة)', description: 'ترطيب مثالي يقي بشرة الرضيع من الجفاف بعد الاستحمام لتغذية البشرة.' },
      { id: 's3-add-5', name: 'زيوت العناية وتدليك الأطفال اللطيفة', category: 'مستحضرات النظافة (الشعر والبشرة)', description: 'تزيد من مرونة الجلد وتساعد بمرحلة التدليك المهدئ قبل النوم المريح.' },
      { id: 's4-toil-5', name: 'كريمات الحماية والوقاية الحاجزة للبشرة', category: 'مستحضرات النظافة (الشعر والبشرة)', description: 'تشكل حاجزاً يحمي طبقة الجلد الخارجية من الملوثات والتهيج والاحمرار.' },
      { id: 's4-diap-1', name: 'حفاضات الأطفال فائقة النعومة لحديثي الولادة', category: 'الحفاضات والمناديل المبللة للأطفال', description: 'امتصاص وحماية تامة مع قناة خاصة بالتهوية لحماية السرة.' },
      { id: 's4-diap-2', name: 'مناديل مبللة مخصصة للبشرة الحساسة جداً', category: 'الحفاضات والمناديل المبللة للأطفال', description: 'مناديل خالية تماماً من الكحول والعطور لتنظيف آمن وحنون للبشرة الحساسة.' },
      { id: 's4-diap-3', name: 'مناديل أطفال مائية نقية (Water Wipes)', category: 'الحفاضات والمناديل المبللة للأطفال', description: 'توفر غسيلاً مائياً طبيعياً بـ 99% من المياه النقية الخالصة دون كيماويات.' },
      { id: 's4-diap-4', name: 'كريمات علاج طفح الحفاض والتهابات المؤخرة', category: 'الحفاضات والمناديل المبللة للأطفال', description: 'تركيبة غنية بأكسيد الزنك لتهدئة وعلاج الاحمرار بسرعة وحماية الجلد.' },
      { id: 's3-add-2', name: 'رضاعات الحليب الطبية المضادة للغازات', category: 'مستلزمات الأطفال والسلامة', description: 'تتميز بصمامات تهوية خاصة تمنع بلع الهواء وتحد من المغص لسلامة الرضيع.' },
      { id: 's4-acc-2', name: 'تعقيم فوري لأدوات وأكواب الأطفال والرضاعات', category: 'مستلزمات الأطفال والسلامة', description: 'تحافظ على أكواب وأكواب التدريب وزجاجات الشرب خالية تماماً من الجراثيم والبكتيريا.' },
      { id: 's4-acc-3', name: 'أجهزة تدفئة رضاعات الأطفال الذكية', category: 'مستلزمات الأطفال والسلامة', description: 'تسخين آمن ومنتظم للحليب للحفاظ على القيمة الغذائية للمكونات والفوائد.' },
      { id: 's4-acc-4', name: 'موزعات وحافظات مسحوق الحليب المحمولة', category: 'مستلزمات الأطفال والسلامة', description: 'عبوات تقسيم وتجهيز مسحوق الحليب مسبقاً للخروج والسفر والراحة.' },
      { id: 's4-acc-5', name: 'لهايات ولهايات التدليك الطبية المهدئة', category: 'مستلزمات الأطفال والسلامة', description: 'لهايات تقويم الأسنان المريحة تدعم تنفس وهدوء الرضيع وتقويم الفم.' },
      { id: 's4-acc-6', name: 'أجهزة المراقبة الذكية لمتابعة سلامة الطفل', category: 'مستلزمات الأطفال والسلامة', description: 'كاميرات عالية الدقة تنقل الصوت والصورة لطمأنتكِ على طفلكِ أثناء بعده.' },
      { id: 's4-acc-7', name: 'صابون غسيل ملابس الأطفال المضاد للحساسية', category: 'مستلزمات الأطفال والسلامة', description: 'سائل تنظيف آمن وخالٍ من الكيماويات القاسية على بشرة الرضيع ونسيج ناعم.' },
      { id: 's4-gear-1', name: 'عربات الأطفال ومقاعد النوم المتكاملة', category: 'وسائل التنقل والمعدات الكبيرة', description: 'عربات مرنة تدعم خيارات التمدد والنوم بآليات أمان متطورة وخفيفة الوزن.' },
      { id: 's4-gear-2', name: 'أنظمة ومقاعد حمل الأطفال المحمولة (صغيرة)', category: 'وسائل التنقل والمعدات الكبيرة', description: 'أدوات حمل مريحة وسهلة الفك والتركيب للتنقل السريع والرحلات.' },
      { id: 's4-gear-3', name: 'مقاعد السيارات الطبية المخصصة للمواليد', category: 'وسائل التنقل والمعدات الكبيرة', description: 'مقاعد مخصصة لحماية الرضيع وحزام أمان خماسي النقاط للطرق الوعرة.' },
      { id: 's4-gear-4', name: 'أسرة الأطفال وسرائر النوم بجانب الأم', category: 'وسائل التنقل والمعدات الكبيرة', description: 'توفر بيئة نوم مستقلة وآمنة تماماً وقريبة من متناول يدكِ اليوم لنوم هادئ.' }
    ]
  },
  {
    id: MilestoneId.INFANT_CARE,
    title: "رعاية الرضيع (6-12 شهر)",
    subtitle: "النمو، الفطام والتطور",
    imageUrl: infantImg,
    description: "مع بدء تناول الأطعمة الصلبة والحبو، تصبح السلامة وأطعمة الفطام هي الأولوية.",
    expertTip: "أدخلي الحبوب المدعمة بالحديد حيث يبدأ مخزون الحديد الطبيعي للطفل بالنفاذ بعد 6 أشهر.",
    clinicalInsight: "التسنين يسبب انزعاجاً كبيراً؛ الحلقات المبردة والجل الخالي من السكر هي وسائل آمنة للراحة.",
    checklist: [
      { id: 's5-nut-1', name: 'حليب الرضع للمرحلة الثانية (6-12 شهر)', category: 'تغذية الرضيع المتكاملة', description: 'يحتوي على مستويات عالية من الحديد ومغذي للرضع الأكثر نشاطاً ونمواً.' },
      { id: 's5-nut-2', name: 'حليب الرضع بتركيبة الراحة (Stage 2 Comfort)', category: 'تغذية الرضيع المتكاملة', description: 'واصل دعم الهضم الصحي وخفض التشنجات والغازات في البطن وتنظيم المغص.' },
      { id: 's5-nut-3', name: 'حليب أطفال تخصصي (مضاد حساسية أو خالي لاكتوز)', category: 'تغذية الرضيع المتكاملة', description: 'خيارات غذائية وعلاجية مخصصة للرضع ذوي المتطلبات الشديدة والحساسية.' },
      { id: 's5-nut-4', name: 'حبوب أرز وشوفان أطفال مدعمة بالحديد بالفواكه', category: 'تغذية الرضيع المتكاملة', description: 'الوجبة الصلبة الأولى والأساسية لبناء وبداية تغذية متكاملة ممتازة.' },
      { id: 's5-nut-5', name: 'أطعمة ومهروس الفواكه العضوية للفطام المتعددة', category: 'تغذية الرضيع المتكاملة', description: 'تساعد على تذوق واستكشاف نكهات صحية جديدة ومفيدة للغاية لبناء الهيكل.' },
      { id: 's5-toil-1', name: 'شامبو لطيف ومغذي لشعر الأطفال المقوي', category: 'مستحضرات نظافة الرضيع', description: 'تنظيف خفيف ولطيف للغاية لخصلات شعر طفلكِ النامية.' },
      { id: 's5-toil-2', name: 'غسول رغوي ناعم ومطهر لجسم الرضيع', category: 'مستحضرات نظافة الرضيع', description: 'تنظيف معتدل ومطهر ومناسب للاستحمام اليومي دون حدوث جفاف للبشرة.' },
      { id: 's5-toil-3', name: 'لوشن الأطفال فائق الترطيب والحماية', category: 'مستحضرات نظافة الرضيع', description: 'يحمي ويحافظ على نعومة وصحة طبقة جلد الرضيع النشط بعد الاستحمام.' },
      { id: 's5-toil-4', name: 'واقي شمس مخصص للأطفال بخصائص آمنة', category: 'مستحضرات نظافة الرضيع', description: 'حماية فائقة ولطيفة من أشعة الشمس الضارة أثناء اللعب في الهواء الطلق.' },
      { id: 's5-diap-1', name: 'حفاضات أطفال مرنة ومقاومة للتسرب', category: 'الحفاضات والنظافة اليومية', description: 'تصميم مريح مع جوانب مطاطية فائقة اللياقة لتلائم حركة حبو الطفل.' },
      { id: 's5-diap-2', name: 'مناديل مبللة نقية ومغدية وحريرية', category: 'الحفاضات والنظافة اليومية', description: 'مناديل سميكة ومرطبة ضرورية لتنظيف وتطهير فوضى الطعام الصلب الحتمي.' },
      { id: 's5-diap-3', name: 'كريمات وقاية وعلاج التهاب منطقة الحفاض', category: 'الحفاضات والنظافة اليومية', description: 'تشكل طبقة عازلة واقية قوية تحمي جلد الرضيع من رطوبة الحفاض والالتهابات.' },
      { id: 's5-acc-1', name: 'جل تسنين مهدئ ومخفف لآلام اللثة العاجل', category: 'مستلزمات نمو وتطور الرضيع', description: 'تركيبة آمنة وخالية من السكر لتلطيف وتهدئة آلام لثة الرضيع أثناء التسنين.' },
      { id: 's5-acc-2', name: 'عضاضات وحلقات تسنين مبردة ومريحة جداً', category: 'مستلزمات نمو وتطور الرضيع', description: 'ألعاب لينة قابلة للتبريد لتهدئة اللثة الملتهبة وتحفيز بزوغ الأسنان.' },
      { id: 's5-acc-3', name: 'لهايات طبية مخصصة للأعمار فوق 6 أشهر', category: 'مستلزمات نمو وتطور الرضيع', description: 'مصممة بشكل ملائم لتقويم الأسنان ودعم النمو الفموي الطبيعي والسليم للطفل.' },
      { id: 's5-acc-4', name: 'أكواب تدريب الشرب مجهزة بمقابض مريحة', category: 'مستلزمات نمو وتطور الرضيع', description: 'تساعد طفلكِ على تعلم الانتقال السهل من الرضاعة إلى الشرب المستقل.' },
      { id: 's5-acc-5', name: 'أوعية تغذية، ملاعق مخصصة، ومرايل للأكل', category: 'مستلزمات نمو وتطور الرضيع', description: 'أدوات مخصصة وعازلة لتوفير معايير أمان تامة وتحبيب تناول الأكل للرضيع.' },
      { id: 's5-acc-6', name: 'سجاد بساط الأنشطة واللعب لرفع الحركة', category: 'مستلزمات نمو وتطور الرضيع', description: 'بساط تفاعلي يشجع الرضيع على الحبو والتحرك وتطوير العضلات الكبيرة.' },
      { id: 's5-acc-7', name: 'ألعاب أطفال ذكية وتنموية لدعم وتقوية المهارات', category: 'مستلزمات نمو وتطور الرضيع', description: 'تنمي التفكير المنطقي، التنسيق الحركي، وتكتشف المفاهيم الأساسية للأشياء والألوان.' },
      { id: 's5-safe-1', name: 'بوابات أمان وحماية للأطفال بالمنزل والدرج', category: 'أنظمة السلامة والحرية بالحركة', description: 'حواجز بوابات متينة تمنع الرضيع من الوصول للمناطق الخطرة كالدرج والمطبخ.' },
      { id: 's5-safe-2', name: 'واقيات السيليكون لحماية زوايا الأثاث والأدراج', category: 'أنظمة السلامة والحرية بالحركة', description: 'تحمي الرضيع المستكشف من الصدمات والارتطام العنيف بالحواف الحادة.' },
      { id: 's5-safe-3', name: 'أجهزة المراقبة الذكية لمتابعة سلامة الطفل', category: 'أنظمة السلامة والحرية بالحركة', description: 'كاميرات عالية الدقة تنقل الصوت والصورة لطمأنتكِ على طفلكِ أثناء بعده.' },
      { id: 's5-safe-4', name: 'ترقية عربات التنقل بخيارات الجلوس العمودي', category: 'أنظمة السلامة والحرية بالحركة', description: 'تدعم تنقلاً مريحاً وجلوساً مستقيماً وممتعاً لاستكشاف العالم الخارجي.' },
      { id: 's5-safe-5', name: 'مقاعد سيارات ذكية متطورة وقابلة للتحويل', category: 'أنظمة السلامة والحرية بالحركة', description: 'تتلاءم وتتعدل وتكبر مع نمو وزن وطول طفلكِ لتوفير أقصى درجات حماية الطريق.' },
      { id: 's5-mom-1', name: 'فيتامينات متعددة لصحة ونشاط الأم المستمر', category: 'رعاية الأم المتواصلة والمقوية', description: 'تمد جسم الأم بالطاقة والنشاط المطلوب لمواكبة متطلبات الأمومة اليومية.' },
      { id: 's5-mom-2', name: 'مستحضر علاج وإصلاح تساقط شعر الأم', category: 'رعاية الأم المتواصلة والمقوية', description: 'منتجات مقوية لتعزيز بصلات الشعر والحد من التساقط المرتبط بالتغير الهرموني.' },
      { id: 's5-mom-3', name: 'مستحضرات استعادة رطوبة ونضارة بشرة الأم', category: 'رعاية الأم المتواصلة والمقوية', description: 'كريمات ترطيب فائقة لإعادة الرونق والنضارة لبشرة الأم المجهدة.' }
    ]
  },
  {
    id: MilestoneId.TODDLER_CARE,
    title: "رعاية الطفل الدارج (1-3 سنوات)",
    subtitle: "الاستقلالية والمناعة",
    imageUrl: toddlerImg,
    description: "يحتاج الدارجون لحليب مخصص ودعم للمناعة. هذه المرحلة تركز أيضاً على نظافة الفم وسلامة المنزل.",
    expertTip: "حليب النمو مدعم بالحديد وفيتامين د لضمان تلبية احتياجات الدارجين اليومية.",
    clinicalInsight: "السنوات الثلاث الأولى هي أسرع فترة لنمو الدماغ. DHA والتغذية السليمة تظل حيوية.",
    checklist: [
      { id: 's6-milk-1', name: 'حليب النمو للأطفال الدارجين (المرحلة الثالثة)', category: 'تغذية ودعم مناعة الدارجين', description: 'يغطي الفجوات الغذائية لدى الأطفال والدارجين الانتقائيين ويدعم تطور مناعة الطفل.' },
      { id: 's6-milk-2', name: 'حليب أطفال كلوت كبّارة (مرحلة التدريب) أو خيارات حليب الماعز والراحة', category: 'تغذية ودعم مناعة الدارجين', description: 'حلول غذائية بديلة تناسب اضطرابات الهضم المؤقتة لدى الأطفال الدارجين.' },
      { id: 's6-milk-3', name: 'شراب فيتامينات أطفال متعددة أو حلوى جيلاتينية مدعمة', category: 'تغذية ودعم مناعة الدارجين', description: 'مكملات سهلة ولذيذة لتعزيز شهية الطفل ومقاومته للأمراض ونموه المتكامل.' },
      { id: 's6-toil-1', name: 'شامبو شعر لطيف مخصص للأطفال الدارجين', category: 'مستحضرات العناية بالنظافة والتحميم للدارجين', description: 'تركيبة خالية من الكيماويات والدموع وتمنح فروة الرأس تنظيفاً صحياً ناعماً.' },
      { id: 's6-toil-2', name: 'بخاخ فك تشابك الشعر المخصص للأطفال', category: 'مستحضرات العناية بالنظافة والتحميم للدارجين', description: 'يجعل تسريح وتمشيط شعر الطفل ناعماً وخالياً من العقد والشد.' },
      { id: 's6-toil-3', name: 'سائل استحمام الأطفال الملطف والرغوي', category: 'مستحضرات العناية بالنظافة والتحميم للدارجين', description: 'ينظف جسم الطفل الدارج بلطف دون التسبب بجفاف بشرته الحساسة.' },
      { id: 's6-toil-4', name: 'لوشن وكريمات مرطبة فائقة النعومة لبشرة الأطفال', category: 'مستحضرات العناية بالنظافة والتحميم للدارجين', description: 'حماية يومية مغذية تحافظ على صحة وليونة بشرة الطفل الصغير.' },
      { id: 's6-toil-5', name: 'واقي شمس مخصص وآمن تماماً للأطفال والرضع', category: 'مستحضرات العناية بالنظافة والتحميم للدارجين', description: 'يحمي خلايا الجلد الحساسة من أضرار الأشعة الكونية الطويلة والمتوسطة أثناء اللعب في الهواء الطلق.' },
      { id: 's6-diap-1', name: 'حفاضات أطفال كلوت كبّارة ومرحلة الاستقلال التدريجية', category: 'الحفاضات ومرحلة التدريب', description: 'تساعد بمرحلة الانتقال والتحرك بسهولة وتدعم البدء بالاستقلالية دون حوادث تسرب.' },
      { id: 's6-diap-2', name: 'حفاضات كلوت سهلة السحب للتدريب على النونية', category: 'الحفاضات ومرحلة التدريب', description: 'توفر شعوراً رائعاً بالملابس الداخلية لتسهيل استخدام المرحاض تدريجياً وبأمان.' },
      { id: 's6-diap-3', name: 'مقاعد ونونيات مرحلة التدريب والتأهيل المريحة', category: 'الحفاضات ومرحلة التدريب', description: 'مقاعد مهيئة خصيصاً تمنح الطفل الأمان وتشجع التدريب الذاتي بكل يسر وبساطة.' },
      { id: 's6-oral-1', name: 'فرش أسنان للأطفال الدارجين بشعيرات فائقة النعومة', category: 'العناية وصحة الفم والأسنان للأطفال', description: 'مصممة خصيصاً بنعومة لحماية اللثة وبدء تأسيس عادات العناية اليومية بالفم والأسنان.' },
      { id: 's6-oral-2', name: 'معجون أسنان طبيعي خالٍ أو منخفض الفلورايد للأطفال', category: 'العناية وصحة الفم والأسنان للأطفال', description: 'آمن ولطيف للغاية ويمنع حدوث التسوس ومناسب تماماً للبلع والتعلم دون قلق.' },
      { id: 's6-play-1', name: 'ألعاب أطفال ذكية وتنموية لدعم وتقوية المهارات', category: 'التعليم والألعاب التطويرية للأطفال', description: 'تنمي التفكير المنطقي، التنسيق الحركي، وتكتشف المفاهيم الأساسية للأشياء والألوان.' },
      { id: 's6-play-2', name: 'ألعاب دفع وعربات مساعدة على المشي للأطفال', category: 'التعليم والألعاب التطويرية للأطفال', description: 'تشجع الطفل على الوقوف بثبات وتدعم توازنه وثقته وتسهل خطواته الأولى بمتعة.' },
      { id: 's6-play-3', name: 'مكعبات البناء وألغاز لقطع التركيب والتركيز للأطفال', category: 'التعليم والألعاب التطويرية للأطفال', description: 'تطور المهارات الحركية الدقيقة والتخطيط الفراغي وزيادة منسوب الصبر والتركيز.' },
      { id: 's6-play-4', name: 'ألعاب وأدوات النشاط واللعب الخارجي للأطفال', category: 'التعليم والألعاب التطويرية للأطفال', description: 'أداة رائعة لتنشيط العضلات واللعب والحركة بالحدائق والمرح الجماعي.' },
      { id: 's6-safe-1', name: 'بوابات أمان متطورة ومزالج حماية للأبواب والغرف والأدراج', category: 'أنظمة السلامة والحرية بالحركة', description: 'أقفال ومزالج متينة وآمنة تمنع الدارج المستكشف من الوصول للأجهزة أو فتح الأدراج الحساسة.' },
      { id: 's6-safe-2', name: 'مقاعد سيارات أطفال دارجين ذكية ومتطورة', category: 'أنظمة السلامة والحرية بالحركة', description: 'أنظمة تثبيت مريحة وحزام أمان متفوق لتوفير أقصى درجات حماية الطريق أثناء ترحال العائلة.' },
      { id: 's6-safe-3', name: 'بدائل عربات الأطفال التقليدية والتنقل التفاعلي الممتع', category: 'أنظمة السلامة والحرية بالحركة', description: 'خيارات فخمة ممتعة وتفاعلية كالدراجة ثلاثية العجلات أو العربات الخفيفة لمزيد من تفاعل الطفل.' },
      { id: 's6-mom-1', name: 'فيتامينات متعددة ومكملات لتعزيز نشاط وحيوية الأم', category: 'العناية اليومية المتواصلة بصحة ونشاط الأم', description: 'تمنح خلايا الجسم النشاط المطلوب لمواكبة تسارع حركة ونمو طفلكِ الدارج دون تعب.' },
      { id: 's6-mom-2', name: 'مستحضرات العناية والترطيب والمحافظة على حيوية بشرة الأم', category: 'العناية اليومية المتواصلة بصحة ونشاط الأم', description: 'طقوس جمال يومية متألقة تنعش نضارة الجلد وتحمي من العوامل البيئية المرهقة.' },
      { id: 's6-mom-3', name: 'زيوت التدليك ومنتجات الاسترخاء وإعادة تعافي الأم بعد الجهد اليومي', category: 'العناية اليومية المتواصلة بصحة ونشاط الأم', description: 'أملاح حمام دافئة وزيوت مهدئة تطلق التوتر والإرهاق العضلي وتمنحكِ نوماً هادئاً مستحقاً.' }
    ]
  }
];
